name: lumina
description: "Lumina Reader - A minimalist EPUB reader with WebDAV sync"
publish_to: 'none'
homepage: https://github.com/MilkFeng/lumina
license: MIT

version: 0.1.2+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^17.1.0

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Storage
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

  # Functional Programming
  fpdart: ^1.2.0

  # EPUB Parsing
  xml: ^6.6.1
  archive: ^4.0.7
  crypto: ^3.0.7
  convert: ^3.1.2
  
  # Reader
  flutter_inappwebview: ^6.1.5
  
  # File Picking & Permissions
  path: ^1.9.1
  
  # App Info & URL Launcher
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3

  # Image Compression
  image: ^4.7.2
  saf_stream: ^0.12.3
  saf_util: ^0.11.0
  
  # Speed Dial FAB
  flutter_speed_dial: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  
  # Testing
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  mockito: ^5.4.4

  # Icon
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: AppSerif
      fonts:
        - asset: assets/fonts/SourceHanSerifSC-ExtraLight-Subset.ttf
          weight: 200
        - asset: assets/fonts/SourceHanSerifSC-Light-Subset.ttf
          weight: 300
        - asset: assets/fonts/SourceHanSerifSC-Regular-Subset.ttf
          weight: 400
        - asset: assets/fonts/SourceHanSerifSC-Medium-Subset.ttf
          weight: 500
        - asset: assets/fonts/SourceHanSerifSC-SemiBold-Subset.ttf
          weight: 600
        - asset: assets/fonts/SourceHanSerifSC-Bold-Subset.ttf
          weight: 700
        - asset: assets/fonts/SourceHanSerifSC-Heavy-Subset.ttf
          weight: 900

    - family: AppSerifContent
      fonts:
        - asset: assets/fonts/SourceHanSerifSC-Regular-Subset.ttf
          weight: 400

  assets:
    - assets/icons/icon.svg