name: Build And Release App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    name: Build Android APKs & AAB
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Create Output Dir
        run: mkdir -p build/outputs

      - name: Build App Bundle
        run: |
          flutter build appbundle --release
          
          NEW_NAME="lumina-${{ github.ref_name }}-bundle-release.aab"
          
          mv build/app/outputs/bundle/release/app-release.aab build/outputs/$NEW_NAME
          echo "Generated $NEW_NAME"

      - name: Build Universal APK
        run: |
          flutter build apk --release
          
          NEW_NAME="lumina-${{ github.ref_name }}-universal-release.apk"
          
          mv build/app/outputs/flutter-apk/app-release.apk build/outputs/$NEW_NAME
          echo "Generated $NEW_NAME"

      - name: Build Split APKs
        run: |
          flutter build apk --release --split-per-abi
          
          cd build/app/outputs/flutter-apk/
          for file in app-*-release.apk; do
            abi=${file#app-}
            abi=${abi%-release.apk}
            
            NEW_NAME="lumina-${{ github.ref_name }}-$abi-release.apk"
            
            mv "$file" "${{ github.workspace }}/build/outputs/$NEW_NAME"
            echo "Generated $NEW_NAME"
          done

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: build/outputs/*

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build IPA (Unsigned)
        run: flutter build ios --release --no-codesign

      - name: Package into IPA
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/

          NAME="lumina-${{ github.ref_name }}-ios-unsigned.ipa"
          zip -r $NAME Payload
          echo "Generated $NAME"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-artifacts
          path: lumina-${{ github.ref_name }}-ios-unsigned.ipa

  create-release:
    name: Create GitHub Release
    needs: [build-ios, build-android]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download iOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-artifacts
          path: artifacts
          
      - name: Download Android Artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-artifacts
          path: artifacts

      - name: Extract Release Notes
        id: extract_notes
        uses: ffurrer2/extract-release-notes@v3

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/**/*.apk
            artifacts/**/*.aab
            artifacts/**/*.ipa
          body: ${{ steps.extract_notes.outputs.release_notes }}
          generate_release_notes: false
          prerelease: false